services:
  - type: web
    name: refl3kt-backend
    env: python
    rootDir: backend/
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn backend.backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        value: G2XdAm-1yhM2gpYM2ILSwznIAq6JEFNY0fPRZXcVW6zh17Dv4DkdQFgASzRx6IDWRuU
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: refl3kt-db
          property: connectionString

databases:
  - name: refl3kt-db
    databaseName: refl3kt_db
    user: refl3kt_user
    plan: free
